check for files

diff --git a/.github/workflows/test_candidate.yml b/.github/workflows/test_candidate.yml
--- a/.github/workflows/test_candidate.yml
+++ b/.github/workflows/test_candidate.yml
@@ -124,9 +124,14 @@ jobs:
         - name: Upload Artifacts
           id: upload_artifacts
           run: |
+            set -e  # Exit immediately if any command returns a non-zero status
             release_tag="v.${{ env.VERSION_NAME }}.2"
             debug_apk=$(find app/build/outputs/apk/debug -name "*.apk")
             release_apk=$(find app/build/outputs/apk/release -name "*.apk")
+            if [[ -z "$debug_apk" || -z "$release_apk" ]]; then
+              echo "Error: APK files not found."
+              exit 1
+            fi
             gh release upload $release_tag $debug_apk $release_apk --clobber
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
