checking the $GITHUB_OUTPUT to get app name

diff --git a/.github/workflows/test_candidate.yml b/.github/workflows/test_candidate.yml
--- a/.github/workflows/test_candidate.yml
+++ b/.github/workflows/test_candidate.yml
@@ -4,140 +4,139 @@ on:
   push:
     branches: [ "test/**" ]
 jobs:
-# build_test:
-
-#   runs-on: ubuntu-latest
-
-#    steps:
-#      - uses: actions/checkout@v3
-#      - name: set up JDK 17
-#        uses: actions/setup-java@v3
-#        with:
-#          java-version: '17'
-#          distribution: 'temurin'
-#          cache: gradle
-#      - name: Create debug keystore
-#        run: |
-#          mkdir -p $HOME/.android
-#          echo "$ANDROID_SDK_ROOT" > $HOME/.android/repositories.cfg
-#          echo "${{ secrets.DEBUG_KEYSTORE }}" | base64 --decode > $HOME/.android/debug.keystore
-#
-#
-#      #      - name: Run unit tests
-#      #        run: ./gradlew test
-#      #      - name: Upload test report directory
-#      #        uses: actions/upload-artifact@v3
-#      #        with:
-#      #          name: TestResults
-#      #          path: build/reports/tests/testDebugUnitTest/
-#      #      - name: Run lint
-#      #        run: ./gradlew lint
-#      #      - name: Upload lint report
-#      #        uses: actions/upload-artifact@v3
-#      #        with:
-#      #          name: LintResult
-#      #          path: build/reports/lint-results*.html
-#      - name: Get branch name
-#        id: extract_branch
-#        run: |
-#          echo "branch=$(echo ${GITHUB_REF##*/})" >>$GITHUB_OUTPUT
-#      - name: Build with Gradle
-#        run: ./gradlew -PverName=${{steps.extract_branch.outputs.branch}} clean build
-#      - name: Set App name
-#        run: |
-#          echo "APP_NAME=$(basename  `ls app/build/outputs/apk/debug/*.apk | head -n 1`)" >> $GITHUB_ENV
-#        id:
-#          app_name
-#      - name: Upload APK
-#        uses: actions/upload-artifact@v4
-#        with:
-#          name: ${{env.APP_NAME}}
-#          path: app/build/outputs/apk/debug/*.apk
-  build_and_release:
+ build_test:
 
       runs-on: ubuntu-latest
-
       steps:
-        - uses: actions/checkout@v3
-        - name: set up JDK 17
-          uses: actions/setup-java@v3
-          with:
-            java-version: '17'
-            distribution: 'temurin'
-            cache: gradle
+      - uses: actions/checkout@v4
+      - name: set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+          cache: gradle
+      - name: Create debug keystore
+        run: |
+          mkdir -p $HOME/.android
+          echo "$ANDROID_SDK_ROOT" > $HOME/.android/repositories.cfg
+          echo "${{ secrets.DEBUG_KEYSTORE }}" | base64 --decode > $HOME/.android/debug.keystore
 
-        - name: Create debug keystore
-          run: |
-            mkdir -p $HOME/.android
-            echo "$ANDROID_SDK_ROOT" > $HOME/.android/repositories.cfg
-            echo "${{ secrets.DEBUG_KEYSTORE }}" | base64 --decode > $HOME/.android/debug.keystore
 
-        #      - name: Run unit tests
-        #        run: ./gradlew test
-        #      - name: Upload test report directory
-        #        uses: actions/upload-artifact@v3
-        #        with:
-        #          name: TestResults
-        #          path: build/reports/tests/testDebugUnitTest/
-        #      - name: Run lint
-        #        run: ./gradlew lint
-        #      - name: Upload lint report
-        #        uses: actions/upload-artifact@v3
-        #        with:
-        #          name: LintResult
-        #          path: build/reports/lint-results*.html
-
-        - name: Set Version Name
-          run: echo "VERSION_NAME=$(./gradlew -q versionName)" >> $GITHUB_ENV
+      #      - name: Run unit tests
+      #        run: ./gradlew test
+      #      - name: Upload test report directory
+      #        uses: actions/upload-artifact@v3
+      #        with:
+      #          name: TestResults
+      #          path: build/reports/tests/testDebugUnitTest/
+      #      - name: Run lint
+      #        run: ./gradlew lint
+      #      - name: Upload lint report
+      #        uses: actions/upload-artifact@v3
+      #        with:
+      #          name: LintResult
+      #          path: build/reports/lint-results*.html
+      - name: Get branch name
+        id: extract_branch
+        run: |
+          echo "branch=$(echo ${GITHUB_REF##*/})" >>$GITHUB_OUTPUT
+      - name: Build with Gradle
+        run: ./gradlew -PverName=${{steps.extract_branch.outputs.branch}} clean build
+      - name: Set App name
+        id:
+          app_name
+        run: |
+          echo "app_name=$(basename  `ls app/build/outputs/apk/debug/*.apk | head -n 1`)" >> $GITHUB_OUTPUT
+      - name: Upload APK
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{steps.app_name.outputs.app_name}}
+          path: app/build/outputs/apk/debug/${{steps.app_name.outputs.app_name}}
+#  build_and_release:
 #
-#        - name: Build with Gradle
-#          run: ./gradlew clean build
-
-
-        - name: Check if Release Exists
-          id: check_release
-          run: |
-            if gh release view "v.${{ env.VERSION_NAME }}" &> /dev/null; then
-              echo "RELEASE_EXISTS=true" >> $GITHUB_ENV
-            else
-              echo "RELEASE_EXISTS=false" >> $GITHUB_ENV
-            fi
-            echo "${{ env.RELEASE_EXISTS }}"
-          env:
-            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        - name: Create or Update Release
-          id: check_release_tag
-          run : echo "${{ env.RELEASE_EXISTS }}"
-        - name: Create or Update Release
-          id: create_or_update_release
-          run: |
-            if env.RELEASE_EXISTS == false
-              echo "New release"
-              # gh release create "v.${{ env.VERSION_NAME }}" --title "Release ${{ env.VERSION_NAME }}"
-          env:
-            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-        - name: Update Release
-          id: update_release
-          run: |
-            if env.RELEASE_EXISTS == true
-              echo "Update release"
-              # gh release edit "v.${{ env.VERSION_NAME }}" --title "Release ${{ env.VERSION_NAME }}"
-            fi
-          env:
-            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-        # - name: Upload Artifacts
-        #   id: upload_artifacts
-        #   run: |
-        #     set -e  # Exit immediately if any command returns a non-zero status
-        #     release_tag="v.${{ env.VERSION_NAME }}"
-        #     debug_apk=$(find app/build/outputs/apk/debug -name "*.apk")
-        #     release_apk=$(find app/build/outputs/apk/release -name "*.apk")
-        #     if [[ -z "$debug_apk" || -z "$release_apk" ]]; then
-        #       echo "Error: APK files not found."
-        #       exit 1
-        #     fi
-#            gh release upload $release_tag $debug_apk $release_apk --clobber
-          # env:
-          #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#      runs-on: ubuntu-latest
+#
+#      steps:
+#        - uses: actions/checkout@v3
+#        - name: set up JDK 17
+#          uses: actions/setup-java@v3
+#          with:
+#            java-version: '17'
+#            distribution: 'temurin'
+#            cache: gradle
+#
+#        - name: Create debug keystore
+#          run: |
+#            mkdir -p $HOME/.android
+#            echo "$ANDROID_SDK_ROOT" > $HOME/.android/repositories.cfg
+#            echo "${{ secrets.DEBUG_KEYSTORE }}" | base64 --decode > $HOME/.android/debug.keystore
+#
+#        #      - name: Run unit tests
+#        #        run: ./gradlew test
+#        #      - name: Upload test report directory
+#        #        uses: actions/upload-artifact@v3
+#        #        with:
+#        #          name: TestResults
+#        #          path: build/reports/tests/testDebugUnitTest/
+#        #      - name: Run lint
+#        #        run: ./gradlew lint
+#        #      - name: Upload lint report
+#        #        uses: actions/upload-artifact@v3
+#        #        with:
+#        #          name: LintResult
+#        #          path: build/reports/lint-results*.html
+#
+#        - name: Set Version Name
+#          run: echo "VERSION_NAME=$(./gradlew -q versionName)" >> $GITHUB_ENV
+##
+##        - name: Build with Gradle
+##          run: ./gradlew clean build
+#
+#
+#        - name: Check if Release Exists
+#          id: check_release
+#          run: |
+#            if gh release view "v.${{ env.VERSION_NAME }}" &> /dev/null; then
+#              echo "RELEASE_EXISTS=true" >> $GITHUB_ENV
+#            else
+#              echo "RELEASE_EXISTS=false" >> $GITHUB_ENV
+#            fi
+#            echo "${{ env.RELEASE_EXISTS }}"
+#          env:
+#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#        - name: Create or Update Release
+#          id: check_release_tag
+#          run : echo "${{ env.RELEASE_EXISTS }}"
+#        - name: Create or Update Release
+#          id: create_or_update_release
+#          run: |
+#            if env.RELEASE_EXISTS == false
+#              echo "New release"
+#              # gh release create "v.${{ env.VERSION_NAME }}" --title "Release ${{ env.VERSION_NAME }}"
+#          env:
+#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#
+#        - name: Update Release
+#          id: update_release
+#          run: |
+#            if env.RELEASE_EXISTS == true
+#              echo "Update release"
+#              # gh release edit "v.${{ env.VERSION_NAME }}" --title "Release ${{ env.VERSION_NAME }}"
+#            fi
+#          env:
+#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#
+#        # - name: Upload Artifacts
+#        #   id: upload_artifacts
+#        #   run: |
+#        #     set -e  # Exit immediately if any command returns a non-zero status
+#        #     release_tag="v.${{ env.VERSION_NAME }}"
+#        #     debug_apk=$(find app/build/outputs/apk/debug -name "*.apk")
+#        #     release_apk=$(find app/build/outputs/apk/release -name "*.apk")
+#        #     if [[ -z "$debug_apk" || -z "$release_apk" ]]; then
+#        #       echo "Error: APK files not found."
+#        #       exit 1
+#        #     fi
+##            gh release upload $release_tag $debug_apk $release_apk --clobber
+#          # env:
+#          #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
